export enum TransactionType {
  CHARGE_WALLET = 'CHARGE_WALLET',
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
  WITHDRAWAL = 'WITHDRAWAL',
  BUY_INTERNET = 'BUY_INTERNET',
  BUY_MOBILE_CHARGE = 'BUY_MOBILE_CHARGE',
  PAY_BILLS = 'PAY_BILLS',
}
