export type JibitTransferState =
  | 'RECEIVED'
  | 'WAITING_FOR_FEE'
  | 'WAITING_FOR_BALANCE'
  | 'CANCELLED'
  | 'SOURCE_PROCESSING'
  | 'DESTINATION_PROCESSING'
  | 'TRANSFERRED'
  | 'FAILED'
  | 'TRANSFERRED_REVERTED'
  | 'FAILED_WRONG';
